export const tables = [
  {
    id: 'uyaf3q3kn8hr2gg',
    name: 'users',
    type: 'base',
    system: false,
    schema: [
      {
        id: '7oetkfv0',
        name: 'name',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: '4pihccxd',
        name: 'email',
        type: 'email',
        system: false,
        required: false,
        options: {
          exceptDomains: null,
          onlyDomains: null,
        },
      },
      {
        id: '2w2jr2rs',
        name: 'password',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'ehajmcir',
        name: 'phone',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'pj3pn0dh',
        name: 'gender',
        type: 'select',
        system: false,
        required: false,
        options: {
          maxSelect: 1,
          values: ['male', 'female'],
        },
      },
      {
        id: 'br3dkwco',
        name: 'role',
        type: 'select',
        system: false,
        required: false,
        options: {
          maxSelect: 1,
          values: ['admin', 'user'],
        },
      },
      {
        id: 'rt5cithf',
        name: 'address',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'rdpquyij',
        name: 'date_of_birth',
        type: 'date',
        system: false,
        required: false,
        options: {
          min: '',
          max: '',
        },
      },
    ],
    indexes: [],
    listRule: null,
    viewRule: null,
    createRule: null,
    updateRule: null,
    deleteRule: null,
    options: {},
  },
  {
    id: 'ebrs6bmtjldgm60',
    name: 'orders',
    type: 'base',
    system: false,
    schema: [
      {
        id: 'en5lxxa5',
        name: 'user_id',
        type: 'relation',
        system: false,
        required: false,
        options: {
          collectionId: 'uyaf3q3kn8hr2gg',
          cascadeDelete: true,
          minSelect: null,
          maxSelect: null,
          displayFields: [],
        },
      },
      {
        id: 'gnrz7utf',
        name: 'session_id',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'o9pogl2f',
        name: 'address',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'qp032ajf',
        name: 'status',
        type: 'select',
        system: false,
        required: false,
        options: {
          maxSelect: 1,
          values: ['pending', 'paid', 'cancelled'],
        },
      },
      {
        id: 'dneijawi',
        name: 'order_email',
        type: 'email',
        system: false,
        required: false,
        options: {
          exceptDomains: null,
          onlyDomains: null,
        },
      },
      {
        id: 'ojnmmv8f',
        name: 'order_phone',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 't3xg7osz',
        name: 'order_date',
        type: 'date',
        system: false,
        required: false,
        options: {
          min: '',
          max: '',
        },
      },
    ],
    indexes: [],
    listRule: null,
    viewRule: null,
    createRule: null,
    updateRule: null,
    deleteRule: null,
    options: {},
  },
  {
    id: '4c53am3vrhl4kpf',
    name: 'order_products',
    type: 'base',
    system: false,
    schema: [
      {
        id: 'zo7p7mlf',
        name: 'order_id',
        type: 'relation',
        system: false,
        required: false,
        options: {
          collectionId: 'ebrs6bmtjldgm60',
          cascadeDelete: true,
          minSelect: null,
          maxSelect: null,
          displayFields: [],
        },
      },
      {
        id: 'nbuln6oh',
        name: 'product_id',
        type: 'relation',
        system: false,
        required: false,
        options: {
          collectionId: 'f2jqd5f1hrt6khg',
          cascadeDelete: true,
          minSelect: null,
          maxSelect: null,
          displayFields: [],
        },
      },
      {
        id: 'kkrdx8ip',
        name: 'quantity',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: null,
        },
      },
    ],
    indexes: [],
    listRule: null,
    viewRule: null,
    createRule: null,
    updateRule: null,
    deleteRule: null,
    options: {},
  },
  {
    id: 'ogln5zchgg7omv6',
    name: 'categories',
    type: 'base',
    system: false,
    schema: [
      {
        id: '4dbpwadz',
        name: 'name',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'tntsjpjr',
        name: 'order',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: null,
        },
      },
      {
        id: 'sfvmgvae',
        name: 'slug',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
    ],
    indexes: [],
    listRule: null,
    viewRule: null,
    createRule: null,
    updateRule: null,
    deleteRule: null,
    options: {},
  },
  {
    id: 'f2jqd5f1hrt6khg',
    name: 'products',
    type: 'base',
    system: false,
    schema: [
      {
        id: 'noxc3ugk',
        name: 'title',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'k3qshyc7',
        name: 'description',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: '3kdhevgq',
        name: 'url',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
      {
        id: 'ic8sxyqa',
        name: 'price',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: null,
        },
      },
      {
        id: 'hc4cbymy',
        name: 'discount',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: null,
        },
      },
      {
        id: '69cg2qm8',
        name: 'rating',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: 5,
        },
      },
      {
        id: 'uztvlg17',
        name: 'quantity',
        type: 'number',
        system: false,
        required: false,
        options: {
          min: 0,
          max: null,
        },
      },
      {
        id: 'ppe57rqb',
        name: 'thumbnail',
        type: 'file',
        system: false,
        required: false,
        options: {
          maxSelect: 1,
          maxSize: 5242880,
          mimeTypes: [],
          thumbs: [],
        },
      },
      {
        id: 'lprpwlt0',
        name: 'images',
        type: 'file',
        system: false,
        required: false,
        options: {
          maxSelect: 10,
          maxSize: 5242880,
          mimeTypes: [],
          thumbs: [],
        },
      },
      {
        id: 'xlzrrurb',
        name: 'category',
        type: 'relation',
        system: false,
        required: false,
        options: {
          collectionId: 'ogln5zchgg7omv6',
          cascadeDelete: false,
          minSelect: null,
          maxSelect: 1,
          displayFields: [],
        },
      },
      {
        id: 'pw2djgcl',
        name: 'brand',
        type: 'text',
        system: false,
        required: false,
        options: {
          min: null,
          max: null,
          pattern: '',
        },
      },
    ],
    indexes: ['CREATE INDEX `idx_kIiPwxG` ON `products` (`url`)'],
    listRule: '',
    viewRule: '',
    createRule: null,
    updateRule: null,
    deleteRule: null,
    options: {},
  },
];
