import path from 'path';

const filePath = path.resolve() + '/backend/database/images/';

export const products = [
  {
    id: '4mjidjh2mgx08z5',
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discount: 13,
    rating: 4.6,
    stock: 94,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: filePath + '1/thumbnail.jpg',
    images: [
      filePath + '1/1.jpg',
      filePath + '1/2.jpg',
      filePath + '1/3.jpg',
      filePath + '1/4.jpg',
      filePath + '1/thumbnail.jpg',
    ],
  },
  {
    id: 'npsxvepod4rxtii',
    title: 'iPhone X',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    price: 899,
    discount: 17,
    rating: 4.4,
    stock: 34,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: filePath + '2/thumbnail.jpg',
    images: [
      filePath + '2/1.jpg',
      filePath + '2/2.jpg',
      filePath + '2/3.jpg',
      filePath + '2/thumbnail.jpg',
    ],
  },
  {
    id: 'ub6b5ul0kcgznpv',
    title: 'Samsung Universe 9',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discount: 15,
    rating: 4.1,
    stock: 36,
    brand: 'Samsung',
    category: 'smartphones',
    thumbnail: filePath + '3/thumbnail.jpg',
    images: [filePath + '3/1.jpg'],
  },
  {
    id: '3knp8bikk3qn5xe',
    title: 'OPPOF19',
    description: 'OPPO F19 is officially announced on April 2021.',
    price: 280,
    discount: 18,
    rating: 4.3,
    stock: 123,
    brand: 'OPPO',
    category: 'smartphones',
    thumbnail: filePath + '4/thumbnail.jpg',
    images: [
      filePath + '4/1.jpg',
      filePath + '4/2.jpg',
      filePath + '4/3.jpg',
      filePath + '4/4.jpg',
      filePath + '4/thumbnail.jpg',
    ],
  },
  {
    id: 'hpx7xwb2f7y8pbh',
    title: 'Huawei P30',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    price: 499,
    discount: 10,
    rating: 3.4,
    stock: 32,
    brand: 'Huawei',
    category: 'smartphones',
    thumbnail: filePath + '5/thumbnail.jpg',
    images: [filePath + '5/1.jpg', filePath + '5/2.jpg', filePath + '5/3.jpg'],
  },
  {
    id: 'jrpz22hlatmrwnk',
    title: 'MacBook Pro',
    description:
      'MacBook Pro 2021 with mini-LED display may launch between September, November',
    price: 1749,
    discount: 11,
    rating: 4.5,
    stock: 83,
    brand: 'Apple',
    category: 'laptops',
    thumbnail: filePath + '6/thumbnail.png',
    images: [
      filePath + '6/1.png',
      filePath + '6/2.jpg',
      filePath + '6/3.png',
      filePath + '6/4.jpg',
    ],
  },
  {
    id: 'r43tbq998ld59ep',
    title: 'Samsung Galaxy Book',
    description:
      'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched',
    price: 1499,
    discount: 4,
    rating: 4.2,
    stock: 50,
    brand: 'Samsung',
    category: 'laptops',
    thumbnail: filePath + '7/thumbnail.jpg',
    images: [
      filePath + '7/1.jpg',
      filePath + '7/2.jpg',
      filePath + '7/3.jpg',
      filePath + '7/thumbnail.jpg',
    ],
  },
  {
    id: 'kphwqs88yb578s2',
    title: 'Microsoft Surface Laptop 4',
    description:
      'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',
    price: 1499,
    discount: 14,
    rating: 4.4,
    stock: 68,
    brand: 'Microsoft Surface',
    category: 'laptops',
    thumbnail: filePath + '8/thumbnail.jpg',
    images: [
      filePath + '8/1.jpg',
      filePath + '8/2.jpg',
      filePath + '8/3.jpg',
      filePath + '8/4.jpg',
      filePath + '8/thumbnail.jpg',
    ],
  },
  {
    id: '0t6d1mv7oylq72p',
    title: 'Infinix INBOOK',
    description:
      'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty',
    price: 1099,
    discount: 11,
    rating: 4.5,
    stock: 96,
    brand: 'Infinix',
    category: 'laptops',
    thumbnail: filePath + '9/thumbnail.jpg',
    images: [
      filePath + '9/1.jpg',
      filePath + '9/2.png',
      filePath + '9/3.png',
      filePath + '9/4.jpg',
      filePath + '9/thumbnail.jpg',
    ],
  },
  {
    id: 'ide8i19zvaw0gb9',
    title: 'HP Pavilion 15-DK1056WM',
    description:
      'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10',
    price: 1099,
    discount: 6,
    rating: 4.6,
    stock: 89,
    brand: 'HP Pavilion',
    category: 'laptops',
    thumbnail: filePath + '10/thumbnail.jpeg',
    images: [
      filePath + '10/1.jpg',
      filePath + '10/2.jpg',
      filePath + '10/3.jpg',
      filePath + '10/thumbnail.jpeg',
    ],
  },
  {
    id: 'g4n2mqtratz0dd0',
    title: 'Leather Straps Wristwatch',
    description: 'Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar',
    price: 120,
    discount: 7,
    rating: 4.6,
    stock: 91,
    brand: 'Naviforce',
    category: 'watches',
    thumbnail: filePath + '61/thumbnail.jpg',
    images: [
      filePath + '61/1.jpg',
      filePath + '61/2.png',
      filePath + '61/3.jpg',
    ],
  },
  {
    id: 'fe1b02bdxw3xu16',
    title: 'Waterproof Leather Brand Watch',
    description:
      'Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours',
    price: 46,
    discount: 3,
    rating: 3.9,
    stock: 95,
    brand: 'SKMEI 9117',
    category: 'watches',
    thumbnail: filePath + '62/thumbnail.jpg',
    images: [filePath + '62/1.jpg', filePath + '62/2.jpg'],
  },
  {
    id: 'igm1lbz7r0na44h',
    title: 'Royal Blue Premium Watch',
    description:
      'Men Silver Chain Royal Blue Premium Watch Latest Analog Watch',
    price: 50,
    discount: 2,
    rating: 4.8,
    stock: 142,
    brand: 'SKMEI 9117',
    category: 'watches',
    thumbnail: filePath + '63/thumbnail.webp',
    images: [
      filePath + '63/1.jpg',
      filePath + '63/2.jpg',
      filePath + '63/3.png',
      filePath + '63/4.jpeg',
    ],
  },
  {
    id: 'ekcvazao2i1kps0',
    title: 'Leather Strap Skeleton Watch',
    description:
      'Leather Strap Skeleton Watch for Men - Stylish and Latest Design',
    price: 46,
    discount: 10,
    rating: 4.9,
    stock: 61,
    brand: 'Strap Skeleton',
    category: 'watches',
    thumbnail: filePath + '64/thumbnail.jpg',
    images: [
      filePath + '64/1.jpg',
      filePath + '64/2.webp',
      filePath + '64/3.jpg',
      filePath + '64/thumbnail.jpg',
    ],
  },
  {
    id: 'w1t2mna3v669b08',
    title: 'Stainless Steel Wrist Watch',
    description:
      "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
    price: 47,
    discount: 17,
    rating: 4.7,
    stock: 94,
    brand: 'Stainless',
    category: 'watches',
    thumbnail: filePath + '65/thumbnail.webp',
    images: [
      filePath + '65/1.jpg',
      filePath + '65/2.webp',
      filePath + '65/3.jpg',
      filePath + '65/4.webp',
      filePath + '65/thumbnail.webp',
    ],
  },
  {
    id: '1y5h96l5s2vq1sz',
    title: 'Steel Analog Couple Watches',
    description: 'Elegant design, Stylish ,Unique & Trendy,Comfortable wear',
    price: 35,
    discount: 3,
    rating: 4.7,
    stock: 24,
    brand: 'Eastern Watches',
    category: 'watches',
    thumbnail: filePath + '66/thumbnail.jpg',
    images: [
      filePath + '66/1.jpg',
      filePath + '66/2.jpg',
      filePath + '66/3.jpg',
      filePath + '66/4.JPG',
      filePath + '66/thumbnail.jpg',
    ],
  },
  {
    id: 'h5v6817ygrxp88y',
    title: 'Fashion Magnetic Wrist Watch',
    description:
      "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
    price: 60,
    discount: 16,
    rating: 4.0,
    stock: 46,
    brand: 'Eastern Watches',
    category: 'watches',
    thumbnail: filePath + '67/thumbnail.jpg',
    images: [
      filePath + '67/1.jpg',
      filePath + '67/2.jpg',
      filePath + '67/3.jpg',
      filePath + '67/4.jpg',
      filePath + '67/thumbnail.jpg',
    ],
  },
  {
    id: 'wmdf7ud4qe7rbcq',
    title: 'Stylish Luxury Digital Watch',
    description:
      'Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls',
    price: 57,
    discount: 9,
    rating: 4.5,
    stock: 77,
    brand: 'Luxury Digital',
    category: 'watches',
    thumbnail: filePath + '68/thumbnail.webp',
    images: [filePath + '68/1.jpg', filePath + '68/2.jpg'],
  },
  {
    id: 'wmu84e0pupx5uv2',
    title: 'Golden Watch Pearls Bracelet Watch',
    description:
      'Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women',
    price: 47,
    discount: 17,
    rating: 4.7,
    stock: 89,
    brand: 'Watch Pearls',
    category: 'watches',
    thumbnail: filePath + '69/thumbnail.jpg',
    images: [
      filePath + '69/1.jpg',
      filePath + '69/2.jpg',
      filePath + '69/3.webp',
      filePath + '69/4.jpg',
      filePath + '69/thumbnail.jpg',
    ],
  },
  {
    id: '419vloc0k9o1b8c',
    title: 'Stainless Steel Women',
    description:
      'Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies',
    price: 35,
    discount: 8,
    rating: 4.0,
    stock: 111,
    brand: 'Bracelet',
    category: 'watches',
    thumbnail: filePath + '70/thumbnail.jpg',
    images: [
      filePath + '70/1.jpg',
      filePath + '70/2.jpg',
      filePath + '70/thumbnail.jpg',
    ],
  },
  {
    id: 'yg8qzg67xmm3ptm',
    title: 'Hyaluronic Acid Serum',
    description:
      "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    price: 19,
    discount: 13,
    rating: 4.1,
    stock: 110,
    brand: "L'Oreal Paris",
    category: 'skincare',
    thumbnail: filePath + '16/thumbnail.jpg',
    images: [
      filePath + '16/1.png',
      filePath + '16/2.webp',
      filePath + '16/3.jpg',
      filePath + '16/4.jpg',
      filePath + '16/thumbnail.jpg',
    ],
  },
  {
    id: 'xtdovlogitjdkjw',
    title: 'Tree Oil 30ml',
    description:
      'Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,',
    price: 12,
    discount: 4,
    rating: 4.5,
    stock: 78,
    brand: 'Hemani Tea',
    category: 'skincare',
    thumbnail: filePath + '17/thumbnail.jpg',
    images: [
      filePath + '17/1.jpg',
      filePath + '17/2.jpg',
      filePath + '17/3.jpg',
      filePath + '17/thumbnail.jpg',
    ],
  },
  {
    id: 's8y2nsmq4kbxyum',
    title: 'Oil Free Moisturizer 100ml',
    description:
      'Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.',
    price: 40,
    discount: 1,
    rating: 4.5,
    stock: 88,
    brand: 'Dermive',
    category: 'skincare',
    thumbnail: filePath + '18/thumbnail.jpg',
    images: [
      filePath + '18/1.jpg',
      filePath + '18/2.jpg',
      filePath + '18/3.jpg',
      filePath + '18/4.jpg',
      filePath + '18/thumbnail.jpg',
    ],
  },
  {
    id: 's88msstnweb7llm',
    title: 'Skin Beauty Serum.',
    description:
      'Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m',
    price: 46,
    discount: 10,
    rating: 4.4,
    stock: 54,
    brand: 'ROREC White Rice',
    category: 'skincare',
    thumbnail: filePath + '19/thumbnail.jpg',
    images: [
      filePath + '19/1.jpg',
      filePath + '19/2.jpg',
      filePath + '19/3.png',
      filePath + '19/thumbnail.jpg',
    ],
  },
  {
    id: '9wbh7808ltjhwsq',
    title: 'Freckle Treatment Cream- 15gm',
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    price: 70,
    discount: 16,
    rating: 4.0,
    stock: 140,
    brand: 'Fair & Clear',
    category: 'skincare',
    thumbnail: filePath + '20/thumbnail.jpg',
    images: [
      filePath + '20/1.jpg',
      filePath + '20/2.jpg',
      filePath + '20/3.jpg',
      filePath + '20/4.jpg',
      filePath + '20/thumbnail.jpg',
    ],
  },
  {
    id: 'bg33ujd5m7z2txh',
    title: 'half sleeves T shirts',
    description:
      'Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands',
    price: 23,
    discount: 12,
    rating: 4.2,
    stock: 132,
    brand: 'Vintage Apparel',
    category: 'shirts',
    thumbnail: filePath + '51/thumbnail.jpg',
    images: [
      filePath + '51/1.png',
      filePath + '51/2.jpg',
      filePath + '51/3.jpg',
      filePath + '51/thumbnail.jpg',
    ],
  },
  {
    id: 'ah0tic0lux8w85i',
    title: 'FREE FIRE T Shirt',
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discount: 14,
    rating: 4.5,
    stock: 128,
    brand: 'FREE FIRE',
    category: 'shirts',
    thumbnail: filePath + '52/thumbnail.jpg',
    images: [
      filePath + '52/1.png',
      filePath + '52/2.png',
      filePath + '52/3.jpg',
      filePath + '52/4.jpg',
      filePath + '52/thumbnail.jpg',
    ],
  },
  {
    id: 'h00pklgihe0i196',
    title: 'printed high quality T shirts',
    description: 'Brand: vintage Apparel ,Export quality',
    price: 35,
    discount: 7,
    rating: 4.8,
    stock: 6,
    brand: 'Vintage Apparel',
    category: 'shirts',
    thumbnail: filePath + '53/thumbnail.jpg',
    images: [
      filePath + '53/1.webp',
      filePath + '53/2.jpg',
      filePath + '53/3.jpg',
      filePath + '53/4.jpg',
      filePath + '53/thumbnail.jpg',
    ],
  },
  {
    id: 'ornj9q8vb5j9hxe',
    title: 'Pubg Printed Graphic T-Shirt',
    description:
      'Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking',
    price: 46,
    discount: 16,
    rating: 4.6,
    stock: 136,
    brand: 'The Warehouse',
    category: 'shirts',
    thumbnail: filePath + '54/thumbnail.jpg',
    images: [
      filePath + '54/1.jpg',
      filePath + '54/2.jpg',
      filePath + '54/3.jpg',
      filePath + '54/4.jpg',
      filePath + '54/thumbnail.jpg',
    ],
  },
  {
    id: 'fvaocxzjhk25a0u',
    title: 'Money Heist Printed Summer T Shirts',
    description: 'Fabric Jercy, Size: M & L Wear Stylish Dual Stiched',
    price: 66,
    discount: 15,
    rating: 4.1,
    stock: 122,
    brand: 'The Warehouse',
    category: 'shirts',
    thumbnail: filePath + '55/thumbnail.jpg',
    images: [
      filePath + '55/1.jpg',
      filePath + '55/2.webp',
      filePath + '55/3.jpg',
      filePath + '55/4.jpg',
      filePath + '55/thumbnail.jpg',
    ],
  },
  {
    id: 'ij7i7e121mff1nx',
    title: 'Bluetooth Aux',
    description:
      'Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3',
    price: 25,
    discount: 10,
    rating: 4.5,
    stock: 22,
    brand: 'Car Aux',
    category: 'automotive',
    thumbnail: filePath + '86/thumbnail.jpg',
    images: [
      filePath + '86/1.jpg',
      filePath + '86/2.webp',
      filePath + '86/3.jpg',
      filePath + '86/4.jpg',
      filePath + '86/thumbnail.jpg',
    ],
  },
  {
    id: '0xs6hdntces0jhi',
    title: 't Temperature Controller Incubator Controller',
    description:
      'Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1',
    price: 40,
    discount: 1,
    rating: 4.5,
    stock: 37,
    brand: 'W1209 DC12V',
    category: 'automotive',
    thumbnail: filePath + '87/thumbnail.jpg',
    images: [
      filePath + '87/1.jpg',
      filePath + '87/2.jpg',
      filePath + '87/3.jpg',
      filePath + '87/4.jpg',
      filePath + '87/thumbnail.jpg',
    ],
  },
  {
    id: 'lucn7r9g5exffrg',
    title: 'TC Reusable Silicone Magic Washing Gloves',
    description:
      'TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose',
    price: 29,
    discount: 3,
    rating: 4.9,
    stock: 42,
    brand: 'TC Reusable',
    category: 'automotive',
    thumbnail: filePath + '88/thumbnail.jpg',
    images: [
      filePath + '88/1.jpg',
      filePath + '88/2.jpg',
      filePath + '88/3.jpg',
      filePath + '88/4.webp',
      filePath + '88/thumbnail.jpg',
    ],
  },
  {
    id: '4nfkhskpas6tiwg',
    title: 'Qualcomm original Car Charger',
    description:
      'best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all',
    price: 40,
    discount: 17,
    rating: 3.8,
    stock: 79,
    brand: 'TC Reusable',
    category: 'automotive',
    thumbnail: filePath + '89/thumbnail.jpg',
    images: [
      filePath + '89/1.jpg',
      filePath + '89/2.jpg',
      filePath + '89/3.jpg',
      filePath + '89/4.jpg',
      filePath + '89/thumbnail.jpg',
    ],
  },
  {
    id: '4p019w40grkr7lu',
    title: 'Cycle Bike Glow',
    description:
      'Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w',
    price: 35,
    discount: 11,
    rating: 3.7,
    stock: 63,
    brand: 'Neon LED Light',
    category: 'automotive',
    thumbnail: filePath + '90/thumbnail.jpg',
    images: [
      filePath + '90/1.jpg',
      filePath + '90/2.jpg',
      filePath + '90/3.jpg',
      filePath + '90/4.jpg',
      filePath + '90/thumbnail.jpg',
    ],
  },
  {
    id: 'v91r4z7h46sew5b',
    title: 'Black Motorbike',
    description:
      'Engine Type:Wet sump, Single Cylinder, Four Stroke, Two Valves, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke:47.0 x 49.5 MM',
    price: 569,
    discount: 13,
    rating: 4.0,
    stock: 115,
    brand: 'METRO 70cc Motorcycle - MR70',
    category: 'motorcycle',
    thumbnail: filePath + '91/thumbnail.jpg',
    images: [
      filePath + '91/1.jpg',
      filePath + '91/2.jpg',
      filePath + '91/3.jpg',
      filePath + '91/4.jpg',
      filePath + '91/thumbnail.jpg',
    ],
  },
  {
    id: '3qkuq7aeetgnfx1',
    title: 'HOT SALE IN EUROPE electric racing motorcycle',
    description:
      'HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles',
    price: 920,
    discount: 1,
    rating: 4.1,
    stock: 22,
    brand: 'BRAVE BULL',
    category: 'motorcycle',
    thumbnail: filePath + '92/thumbnail.jpg',
    images: [
      filePath + '92/1.jpg',
      filePath + '92/2.jpg',
      filePath + '92/3.jpg',
      filePath + '92/4.jpg',
    ],
  },
  {
    id: 'inlx5ozxsgsapib',
    title: 'Automatic Motor Gas Motorcycles',
    description:
      '150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter',
    price: 1050,
    discount: 3,
    rating: 4.8,
    stock: 127,
    brand: 'shock absorber',
    category: 'motorcycle',
    thumbnail: filePath + '93/thumbnail.jpg',
    images: [
      filePath + '93/1.jpg',
      filePath + '93/2.jpg',
      filePath + '93/3.jpg',
      filePath + '93/4.jpg',
      filePath + '93/thumbnail.jpg',
    ],
  },
  {
    id: '49lr7neiumunto7',
    title: 'new arrivals Fashion motocross goggles',
    description:
      'new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle',
    price: 900,
    discount: 3,
    rating: 4.0,
    stock: 109,
    brand: 'JIEPOLLY',
    category: 'motorcycle',
    thumbnail: filePath + '94/thumbnail.webp',
    images: [
      filePath + '94/1.webp',
      filePath + '94/2.jpg',
      filePath + '94/3.jpg',
      filePath + '94/thumbnail.webp',
    ],
  },
  {
    id: 'xqq1vmjouq3e9mj',
    title: 'Wholesale cargo lashing Belt',
    description:
      'Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle',
    price: 930,
    discount: 17,
    rating: 4.2,
    stock: 144,
    brand: 'Xiangle',
    category: 'motorcycle',
    thumbnail: filePath + '95/thumbnail.jpg',
    images: [
      filePath + '95/1.jpg',
      filePath + '95/2.jpg',
      filePath + '95/3.jpg',
      filePath + '95/4.jpg',
      filePath + '95/thumbnail.jpg',
    ],
  },
];
